/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace MovieManager {
      
    export type MovieStruct = {id: BigNumberish, title: string, ageRestriction: BigNumberish, metadataURI: string, owner: AddressLike, active: boolean}

    export type MovieStructOutput = [id: bigint, title: string, ageRestriction: bigint, metadataURI: string, owner: string, active: boolean] & {id: bigint, title: string, ageRestriction: bigint, metadataURI: string, owner: string, active: boolean }
  

    export type ShowStruct = {id: BigNumberish, movieId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish, totalSeats: BigNumberish, availableSeats: BigNumberish, active: boolean}

    export type ShowStructOutput = [id: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint, totalSeats: bigint, availableSeats: bigint, active: boolean] & {id: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint, totalSeats: bigint, availableSeats: bigint, active: boolean }
  
    }

  export interface MovieManagerInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "THEATER_OWNER_ROLE" | "addMovie" | "addShow" | "deactivateMovie" | "deactivateShow" | "decrementAvailableSeats" | "getActiveMovies" | "getAllMovies" | "getAllShows" | "getMovie" | "getMovieShows" | "getRoleAdmin" | "getShow" | "grantRole" | "hasRole" | "incrementAvailableSeats" | "movieShows" | "movies" | "nextMovieId" | "nextShowId" | "registerTheaterOwner" | "renounceRole" | "revokeRole" | "shows" | "supportsInterface" | "updateMovie" | "updateShow"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MovieAdded" | "MovieDeactivated" | "MovieUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "ShowAdded" | "ShowDeactivated" | "ShowUpdated" | "TheaterOwnerRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'THEATER_OWNER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addMovie', values: [string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'addShow', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deactivateMovie', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deactivateShow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'decrementAvailableSeats', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getActiveMovies', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllMovies', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllShows', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMovie', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMovieShows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getShow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'incrementAvailableSeats', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'movieShows', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'movies', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextMovieId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextShowId', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerTheaterOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'shows', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateMovie', values: [BigNumberish, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'updateShow', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'THEATER_OWNER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addMovie', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addShow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateMovie', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateShow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decrementAvailableSeats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveMovies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllMovies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllShows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMovie', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMovieShows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementAvailableSeats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'movieShows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'movies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextMovieId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextShowId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerTheaterOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMovie', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateShow', data: BytesLike): Result;
  }

  
    export namespace MovieAddedEvent {
      export type InputTuple = [movieId: BigNumberish, title: string, owner: AddressLike];
      export type OutputTuple = [movieId: bigint, title: string, owner: string];
      export interface OutputObject {movieId: bigint, title: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MovieDeactivatedEvent {
      export type InputTuple = [movieId: BigNumberish];
      export type OutputTuple = [movieId: bigint];
      export interface OutputObject {movieId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MovieUpdatedEvent {
      export type InputTuple = [movieId: BigNumberish, title: string];
      export type OutputTuple = [movieId: bigint, title: string];
      export interface OutputObject {movieId: bigint, title: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShowAddedEvent {
      export type InputTuple = [showId: BigNumberish, movieId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish];
      export type OutputTuple = [showId: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint];
      export interface OutputObject {showId: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShowDeactivatedEvent {
      export type InputTuple = [showId: BigNumberish];
      export type OutputTuple = [showId: bigint];
      export interface OutputObject {showId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShowUpdatedEvent {
      export type InputTuple = [showId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish];
      export type OutputTuple = [showId: bigint, showtime: bigint, ticketPrice: bigint];
      export interface OutputObject {showId: bigint, showtime: bigint, ticketPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TheaterOwnerRegisteredEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MovieManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): MovieManager;
    waitForDeployment(): Promise<this>;

    interface: MovieManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    THEATER_OWNER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addMovie: TypedContractMethod<
      [title: string, ageRestriction: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    addShow: TypedContractMethod<
      [movieId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish, totalSeats: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    deactivateMovie: TypedContractMethod<
      [movieId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deactivateShow: TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    decrementAvailableSeats: TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getActiveMovies: TypedContractMethod<
      [],
      [MovieManager.MovieStructOutput[]],
      'view'
    >
    

    
    getAllMovies: TypedContractMethod<
      [],
      [MovieManager.MovieStructOutput[]],
      'view'
    >
    

    
    getAllShows: TypedContractMethod<
      [],
      [MovieManager.ShowStructOutput[]],
      'view'
    >
    

    
    getMovie: TypedContractMethod<
      [movieId: BigNumberish, ],
      [MovieManager.MovieStructOutput],
      'view'
    >
    

    
    getMovieShows: TypedContractMethod<
      [movieId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getShow: TypedContractMethod<
      [showId: BigNumberish, ],
      [MovieManager.ShowStructOutput],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    incrementAvailableSeats: TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    movieShows: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    movies: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, string, boolean] & {id: bigint, title: string, ageRestriction: bigint, metadataURI: string, owner: string, active: boolean }],
      'view'
    >
    

    
    nextMovieId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextShowId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerTheaterOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    shows: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint, totalSeats: bigint, availableSeats: bigint, active: boolean }],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    updateMovie: TypedContractMethod<
      [movieId: BigNumberish, title: string, ageRestriction: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateShow: TypedContractMethod<
      [showId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'THEATER_OWNER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addMovie'): TypedContractMethod<
      [title: string, ageRestriction: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addShow'): TypedContractMethod<
      [movieId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish, totalSeats: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deactivateMovie'): TypedContractMethod<
      [movieId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deactivateShow'): TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decrementAvailableSeats'): TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getActiveMovies'): TypedContractMethod<
      [],
      [MovieManager.MovieStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllMovies'): TypedContractMethod<
      [],
      [MovieManager.MovieStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllShows'): TypedContractMethod<
      [],
      [MovieManager.ShowStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMovie'): TypedContractMethod<
      [movieId: BigNumberish, ],
      [MovieManager.MovieStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMovieShows'): TypedContractMethod<
      [movieId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getShow'): TypedContractMethod<
      [showId: BigNumberish, ],
      [MovieManager.ShowStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'incrementAvailableSeats'): TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'movieShows'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'movies'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, string, string, boolean] & {id: bigint, title: string, ageRestriction: bigint, metadataURI: string, owner: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'nextMovieId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextShowId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerTheaterOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shows'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint, totalSeats: bigint, availableSeats: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'updateMovie'): TypedContractMethod<
      [movieId: BigNumberish, title: string, ageRestriction: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateShow'): TypedContractMethod<
      [showId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MovieAdded'): TypedContractEvent<MovieAddedEvent.InputTuple, MovieAddedEvent.OutputTuple, MovieAddedEvent.OutputObject>;
getEvent(key: 'MovieDeactivated'): TypedContractEvent<MovieDeactivatedEvent.InputTuple, MovieDeactivatedEvent.OutputTuple, MovieDeactivatedEvent.OutputObject>;
getEvent(key: 'MovieUpdated'): TypedContractEvent<MovieUpdatedEvent.InputTuple, MovieUpdatedEvent.OutputTuple, MovieUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'ShowAdded'): TypedContractEvent<ShowAddedEvent.InputTuple, ShowAddedEvent.OutputTuple, ShowAddedEvent.OutputObject>;
getEvent(key: 'ShowDeactivated'): TypedContractEvent<ShowDeactivatedEvent.InputTuple, ShowDeactivatedEvent.OutputTuple, ShowDeactivatedEvent.OutputObject>;
getEvent(key: 'ShowUpdated'): TypedContractEvent<ShowUpdatedEvent.InputTuple, ShowUpdatedEvent.OutputTuple, ShowUpdatedEvent.OutputObject>;
getEvent(key: 'TheaterOwnerRegistered'): TypedContractEvent<TheaterOwnerRegisteredEvent.InputTuple, TheaterOwnerRegisteredEvent.OutputTuple, TheaterOwnerRegisteredEvent.OutputObject>;

    filters: {
      
      'MovieAdded(uint256,string,address)': TypedContractEvent<MovieAddedEvent.InputTuple, MovieAddedEvent.OutputTuple, MovieAddedEvent.OutputObject>;
      MovieAdded: TypedContractEvent<MovieAddedEvent.InputTuple, MovieAddedEvent.OutputTuple, MovieAddedEvent.OutputObject>;
    

      'MovieDeactivated(uint256)': TypedContractEvent<MovieDeactivatedEvent.InputTuple, MovieDeactivatedEvent.OutputTuple, MovieDeactivatedEvent.OutputObject>;
      MovieDeactivated: TypedContractEvent<MovieDeactivatedEvent.InputTuple, MovieDeactivatedEvent.OutputTuple, MovieDeactivatedEvent.OutputObject>;
    

      'MovieUpdated(uint256,string)': TypedContractEvent<MovieUpdatedEvent.InputTuple, MovieUpdatedEvent.OutputTuple, MovieUpdatedEvent.OutputObject>;
      MovieUpdated: TypedContractEvent<MovieUpdatedEvent.InputTuple, MovieUpdatedEvent.OutputTuple, MovieUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'ShowAdded(uint256,uint256,uint256,uint256)': TypedContractEvent<ShowAddedEvent.InputTuple, ShowAddedEvent.OutputTuple, ShowAddedEvent.OutputObject>;
      ShowAdded: TypedContractEvent<ShowAddedEvent.InputTuple, ShowAddedEvent.OutputTuple, ShowAddedEvent.OutputObject>;
    

      'ShowDeactivated(uint256)': TypedContractEvent<ShowDeactivatedEvent.InputTuple, ShowDeactivatedEvent.OutputTuple, ShowDeactivatedEvent.OutputObject>;
      ShowDeactivated: TypedContractEvent<ShowDeactivatedEvent.InputTuple, ShowDeactivatedEvent.OutputTuple, ShowDeactivatedEvent.OutputObject>;
    

      'ShowUpdated(uint256,uint256,uint256)': TypedContractEvent<ShowUpdatedEvent.InputTuple, ShowUpdatedEvent.OutputTuple, ShowUpdatedEvent.OutputObject>;
      ShowUpdated: TypedContractEvent<ShowUpdatedEvent.InputTuple, ShowUpdatedEvent.OutputTuple, ShowUpdatedEvent.OutputObject>;
    

      'TheaterOwnerRegistered(address)': TypedContractEvent<TheaterOwnerRegisteredEvent.InputTuple, TheaterOwnerRegisteredEvent.OutputTuple, TheaterOwnerRegisteredEvent.OutputObject>;
      TheaterOwnerRegistered: TypedContractEvent<TheaterOwnerRegisteredEvent.InputTuple, TheaterOwnerRegisteredEvent.OutputTuple, TheaterOwnerRegisteredEvent.OutputObject>;
    
    };
  }