/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AgeVerificationInterface extends Interface {
    getFunction(nameOrSignature: "checkVerification" | "isVerified" | "selfVerify" | "updateVerifier" | "verificationTimestamp" | "verifier" | "verifyAge"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgeVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'checkVerification', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isVerified', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'selfVerify', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'updateVerifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verificationTimestamp', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyAge', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'checkVerification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'selfVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verificationTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyAge', data: BytesLike): Result;
  }

  
    export namespace AgeVerifiedEvent {
      export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [user: string, timestamp: bigint];
      export interface OutputObject {user: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgeVerification extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgeVerification;
    waitForDeployment(): Promise<this>;

    interface: AgeVerificationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    checkVerification: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isVerified: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    selfVerify: TypedContractMethod<
      [litAttestationProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateVerifier: TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verificationTimestamp: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyAge: TypedContractMethod<
      [user: AddressLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'checkVerification'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isVerified'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'selfVerify'): TypedContractMethod<
      [litAttestationProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateVerifier'): TypedContractMethod<
      [newVerifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verificationTimestamp'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyAge'): TypedContractMethod<
      [user: AddressLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgeVerified'): TypedContractEvent<AgeVerifiedEvent.InputTuple, AgeVerifiedEvent.OutputTuple, AgeVerifiedEvent.OutputObject>;

    filters: {
      
      'AgeVerified(address,uint256)': TypedContractEvent<AgeVerifiedEvent.InputTuple, AgeVerifiedEvent.OutputTuple, AgeVerifiedEvent.OutputObject>;
      AgeVerified: TypedContractEvent<AgeVerifiedEvent.InputTuple, AgeVerifiedEvent.OutputTuple, AgeVerifiedEvent.OutputObject>;
    
    };
  }