/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AgeVerification', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgeVerification__factory>
getContractFactory(name: 'MockPYUSD', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPYUSD__factory>
getContractFactory(name: 'MovieManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MovieManager__factory>
getContractFactory(name: 'MovieManagerWithAvail', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MovieManagerWithAvail__factory>
getContractFactory(name: 'IAgeVerification', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAgeVerification__factory>
getContractFactory(name: 'IMovieManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMovieManager__factory>
getContractFactory(name: 'ITicketNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITicketNFT__factory>
getContractFactory(name: 'TicketEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TicketEscrow__factory>
getContractFactory(name: 'TicketNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TicketNFT__factory>

  getContractAt(name: 'AgeVerification', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgeVerification>
getContractAt(name: 'MockPYUSD', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPYUSD>
getContractAt(name: 'MovieManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MovieManager>
getContractAt(name: 'MovieManagerWithAvail', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MovieManagerWithAvail>
getContractAt(name: 'IAgeVerification', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAgeVerification>
getContractAt(name: 'IMovieManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMovieManager>
getContractAt(name: 'ITicketNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITicketNFT>
getContractAt(name: 'TicketEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TicketEscrow>
getContractAt(name: 'TicketNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TicketNFT>

  deployContract(name: 'AgeVerification', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgeVerification>
deployContract(name: 'MockPYUSD', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPYUSD>
deployContract(name: 'MovieManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MovieManager>
deployContract(name: 'MovieManagerWithAvail', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MovieManagerWithAvail>
deployContract(name: 'IAgeVerification', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgeVerification>
deployContract(name: 'IMovieManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMovieManager>
deployContract(name: 'ITicketNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITicketNFT>
deployContract(name: 'TicketEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TicketEscrow>
deployContract(name: 'TicketNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TicketNFT>

  deployContract(name: 'AgeVerification', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgeVerification>
deployContract(name: 'MockPYUSD', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPYUSD>
deployContract(name: 'MovieManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MovieManager>
deployContract(name: 'MovieManagerWithAvail', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MovieManagerWithAvail>
deployContract(name: 'IAgeVerification', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgeVerification>
deployContract(name: 'IMovieManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMovieManager>
deployContract(name: 'ITicketNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITicketNFT>
deployContract(name: 'TicketEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TicketEscrow>
deployContract(name: 'TicketNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TicketNFT>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  