/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMovieManager, IMovieManagerInterface } from "../../TicketEscrow.sol/IMovieManager.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "showId",
        "type": "uint256"
      }
    ],
    "name": "decrementAvailableSeats",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "movieId",
        "type": "uint256"
      }
    ],
    "name": "getMovie",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "title",
            "type": "string"
          },
          {
            "internalType": "uint8",
            "name": "ageRestriction",
            "type": "uint8"
          },
          {
            "internalType": "string",
            "name": "metadataURI",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          }
        ],
        "internalType": "struct Movie",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "showId",
        "type": "uint256"
      }
    ],
    "name": "getShow",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "movieId",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "showtime",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "ticketPrice",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalSeats",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "availableSeats",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          }
        ],
        "internalType": "struct Show",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "showId",
        "type": "uint256"
      }
    ],
    "name": "incrementAvailableSeats",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMovieManager__factory {
    static readonly abi = _abi;
    static createInterface(): IMovieManagerInterface {
      return new Interface(_abi) as IMovieManagerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMovieManager {
      return new Contract(address, _abi, runner) as unknown as IMovieManager;
    }
  }
  