/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITicketNFT, ITicketNFTInterface } from "../../TicketEscrow.sol/ITicketNFT.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "movieId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "encryptedURI",
        "type": "string"
      }
    ],
    "name": "mintTicket",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ITicketNFT__factory {
    static readonly abi = _abi;
    static createInterface(): ITicketNFTInterface {
      return new Interface(_abi) as ITicketNFTInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITicketNFT {
      return new Contract(address, _abi, runner) as unknown as ITicketNFT;
    }
  }
  