/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
    export type MovieStruct = {id: BigNumberish, title: string, ageRestriction: BigNumberish, metadataURI: string, owner: AddressLike, active: boolean}

    export type MovieStructOutput = [id: bigint, title: string, ageRestriction: bigint, metadataURI: string, owner: string, active: boolean] & {id: bigint, title: string, ageRestriction: bigint, metadataURI: string, owner: string, active: boolean }
  

    export type ShowStruct = {id: BigNumberish, movieId: BigNumberish, showtime: BigNumberish, ticketPrice: BigNumberish, totalSeats: BigNumberish, availableSeats: BigNumberish, active: boolean}

    export type ShowStructOutput = [id: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint, totalSeats: bigint, availableSeats: bigint, active: boolean] & {id: bigint, movieId: bigint, showtime: bigint, ticketPrice: bigint, totalSeats: bigint, availableSeats: bigint, active: boolean }
  

  export interface IMovieManagerInterface extends Interface {
    getFunction(nameOrSignature: "decrementAvailableSeats" | "getMovie" | "getShow" | "incrementAvailableSeats"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'decrementAvailableSeats', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMovie', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getShow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'incrementAvailableSeats', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'decrementAvailableSeats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMovie', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementAvailableSeats', data: BytesLike): Result;
  }

  

  export interface IMovieManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMovieManager;
    waitForDeployment(): Promise<this>;

    interface: IMovieManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    decrementAvailableSeats: TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getMovie: TypedContractMethod<
      [movieId: BigNumberish, ],
      [MovieStructOutput],
      'view'
    >
    

    
    getShow: TypedContractMethod<
      [showId: BigNumberish, ],
      [ShowStructOutput],
      'view'
    >
    

    
    incrementAvailableSeats: TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'decrementAvailableSeats'): TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMovie'): TypedContractMethod<
      [movieId: BigNumberish, ],
      [MovieStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getShow'): TypedContractMethod<
      [showId: BigNumberish, ],
      [ShowStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'incrementAvailableSeats'): TypedContractMethod<
      [showId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }