/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace TicketEscrow {
      
    export type PurchaseStruct = {showId: BigNumberish, movieId: BigNumberish, buyer: AddressLike, amount: BigNumberish, seatNumbers: BigNumberish[], issued: boolean, timestamp: BigNumberish}

    export type PurchaseStructOutput = [showId: bigint, movieId: bigint, buyer: string, amount: bigint, seatNumbers: bigint[], issued: boolean, timestamp: bigint] & {showId: bigint, movieId: bigint, buyer: string, amount: bigint, seatNumbers: bigint[], issued: boolean, timestamp: bigint }
  
    }

  export interface TicketEscrowInterface extends Interface {
    getFunction(nameOrSignature: "ageVerification" | "buyTicket" | "getPurchase" | "getShowBookingStats" | "getShowPurchases" | "getUserPurchases" | "isSeatTaken" | "issueTicket" | "movieManager" | "nextPurchaseId" | "purchases" | "pyusd" | "requestRefund" | "showPurchases" | "showSeatTaken" | "ticketNFT" | "userPurchases"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FundsWithdrawn" | "RefundProcessed" | "TicketIssued" | "TicketPurchased"): EventFragment;

    encodeFunctionData(functionFragment: 'ageVerification', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyTicket', values: [BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'getPurchase', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getShowBookingStats', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getShowPurchases', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserPurchases', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isSeatTaken', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'issueTicket', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'movieManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextPurchaseId', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchases', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pyusd', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestRefund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'showPurchases', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'showSeatTaken', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ticketNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'userPurchases', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ageVerification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPurchase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShowBookingStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShowPurchases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserPurchases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSeatTaken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'movieManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextPurchaseId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pyusd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'showPurchases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'showSeatTaken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userPurchases', data: BytesLike): Result;
  }

  
    export namespace FundsWithdrawnEvent {
      export type InputTuple = [theaterOwner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [theaterOwner: string, amount: bigint];
      export interface OutputObject {theaterOwner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundProcessedEvent {
      export type InputTuple = [purchaseId: BigNumberish, buyer: AddressLike, customerAmount: BigNumberish, theaterOwnerAmount: BigNumberish];
      export type OutputTuple = [purchaseId: bigint, buyer: string, customerAmount: bigint, theaterOwnerAmount: bigint];
      export interface OutputObject {purchaseId: bigint, buyer: string, customerAmount: bigint, theaterOwnerAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketIssuedEvent {
      export type InputTuple = [purchaseId: BigNumberish, ticketId: BigNumberish, buyer: AddressLike];
      export type OutputTuple = [purchaseId: bigint, ticketId: bigint, buyer: string];
      export interface OutputObject {purchaseId: bigint, ticketId: bigint, buyer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketPurchasedEvent {
      export type InputTuple = [purchaseId: BigNumberish, showId: BigNumberish, buyer: AddressLike, amount: BigNumberish, seatNumbers: BigNumberish[]];
      export type OutputTuple = [purchaseId: bigint, showId: bigint, buyer: string, amount: bigint, seatNumbers: bigint[]];
      export interface OutputObject {purchaseId: bigint, showId: bigint, buyer: string, amount: bigint, seatNumbers: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TicketEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): TicketEscrow;
    waitForDeployment(): Promise<this>;

    interface: TicketEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ageVerification: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buyTicket: TypedContractMethod<
      [showId: BigNumberish, seatNumbers: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    getPurchase: TypedContractMethod<
      [purchaseId: BigNumberish, ],
      [TicketEscrow.PurchaseStructOutput],
      'view'
    >
    

    
    getShowBookingStats: TypedContractMethod<
      [showId: BigNumberish, ],
      [[bigint, bigint, bigint] & {totalBookings: bigint, totalRevenue: bigint, ticketsSold: bigint }],
      'view'
    >
    

    
    getShowPurchases: TypedContractMethod<
      [showId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getUserPurchases: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    isSeatTaken: TypedContractMethod<
      [showId: BigNumberish, seatNumber: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    issueTicket: TypedContractMethod<
      [purchaseId: BigNumberish, encryptedTicketURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    movieManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nextPurchaseId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    purchases: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, boolean, bigint] & {showId: bigint, movieId: bigint, buyer: string, amount: bigint, issued: boolean, timestamp: bigint }],
      'view'
    >
    

    
    pyusd: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    requestRefund: TypedContractMethod<
      [purchaseId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    showPurchases: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    showSeatTaken: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    ticketNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    userPurchases: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ageVerification'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyTicket'): TypedContractMethod<
      [showId: BigNumberish, seatNumbers: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPurchase'): TypedContractMethod<
      [purchaseId: BigNumberish, ],
      [TicketEscrow.PurchaseStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getShowBookingStats'): TypedContractMethod<
      [showId: BigNumberish, ],
      [[bigint, bigint, bigint] & {totalBookings: bigint, totalRevenue: bigint, ticketsSold: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getShowPurchases'): TypedContractMethod<
      [showId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getUserPurchases'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isSeatTaken'): TypedContractMethod<
      [showId: BigNumberish, seatNumber: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issueTicket'): TypedContractMethod<
      [purchaseId: BigNumberish, encryptedTicketURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'movieManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextPurchaseId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'purchases'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, boolean, bigint] & {showId: bigint, movieId: bigint, buyer: string, amount: bigint, issued: boolean, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'pyusd'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requestRefund'): TypedContractMethod<
      [purchaseId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'showPurchases'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'showSeatTaken'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ticketNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userPurchases'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'FundsWithdrawn'): TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
getEvent(key: 'RefundProcessed'): TypedContractEvent<RefundProcessedEvent.InputTuple, RefundProcessedEvent.OutputTuple, RefundProcessedEvent.OutputObject>;
getEvent(key: 'TicketIssued'): TypedContractEvent<TicketIssuedEvent.InputTuple, TicketIssuedEvent.OutputTuple, TicketIssuedEvent.OutputObject>;
getEvent(key: 'TicketPurchased'): TypedContractEvent<TicketPurchasedEvent.InputTuple, TicketPurchasedEvent.OutputTuple, TicketPurchasedEvent.OutputObject>;

    filters: {
      
      'FundsWithdrawn(address,uint256)': TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
      FundsWithdrawn: TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
    

      'RefundProcessed(uint256,address,uint256,uint256)': TypedContractEvent<RefundProcessedEvent.InputTuple, RefundProcessedEvent.OutputTuple, RefundProcessedEvent.OutputObject>;
      RefundProcessed: TypedContractEvent<RefundProcessedEvent.InputTuple, RefundProcessedEvent.OutputTuple, RefundProcessedEvent.OutputObject>;
    

      'TicketIssued(uint256,uint256,address)': TypedContractEvent<TicketIssuedEvent.InputTuple, TicketIssuedEvent.OutputTuple, TicketIssuedEvent.OutputObject>;
      TicketIssued: TypedContractEvent<TicketIssuedEvent.InputTuple, TicketIssuedEvent.OutputTuple, TicketIssuedEvent.OutputObject>;
    

      'TicketPurchased(uint256,uint256,address,uint256,uint256[])': TypedContractEvent<TicketPurchasedEvent.InputTuple, TicketPurchasedEvent.OutputTuple, TicketPurchasedEvent.OutputObject>;
      TicketPurchased: TypedContractEvent<TicketPurchasedEvent.InputTuple, TicketPurchasedEvent.OutputTuple, TicketPurchasedEvent.OutputObject>;
    
    };
  }