# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
  - id: 11155111
    start_block: 0
    contracts:
      - name: MovieManager
        address:
          - 0x0d9C35FA08D03b1106FceBF0aa097F92C95E8b88
        events:
          - name: MovieAdded
            handler: MovieManager.MovieAdded.handler
          - name: ShowAdded
            handler: MovieManager.ShowAdded.handler
      - name: TicketEscrow
        address:
          - 0x5BAFcCD137A7318e2dd1b3c696A035940e9c09E2
        events:
          - name: RefundProcessed
            handler: TicketEscrow.RefundProcessed.handler
          - name: TicketPurchased
            handler: TicketEscrow.TicketPurchased.handler

field_selection:
  transaction_fields:
    - "hash"

unordered_multichain_mode: true
preload_handlers: true
