type MovieManager_MovieAdded @entity {
  id: ID!
  movieId: BigInt!
  title: String!
  owner: String!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
}
 
type MovieManager_ShowAdded @entity {
  id: ID!
  showId: BigInt!
  movieId: BigInt!
  showtime: BigInt!
  ticketPrice: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
}
 
type TicketEscrow_RefundProcessed @entity {
  id: ID!
  purchaseId: BigInt!
  buyer: String!
  customerAmount: BigInt!
  theaterOwnerAmount: BigInt!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
}
 
type TicketEscrow_TicketPurchased @entity {
  id: ID!
  purchaseId: BigInt!
  showId: BigInt!
  buyer: String!
  amount: BigInt!
  seatNumbers: [BigInt!]!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: String!
}